// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYbMxAPny_Kz5AbwUQpR9Kan6ZFgt080',
    appId: '1:64723911142:web:d41d90fd293f31545e1627',
    messagingSenderId: '64723911142',
    projectId: 'proaluno-81799',
    authDomain: 'proaluno-81799.firebaseapp.com',
    storageBucket: 'proaluno-81799.firebasestorage.app',
    measurementId: 'G-ESCEGBG27D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtOi-5xQR0EnwW_hZ6h6LqEuDH6KkymCg',
    appId: '1:64723911142:android:7a27d99d018e3dae5e1627',
    messagingSenderId: '64723911142',
    projectId: 'proaluno-81799',
    storageBucket: 'proaluno-81799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVT6Xpm3Ve7-e2DHvcC3q3Z2mD4CvV18',
    appId: '1:64723911142:ios:634d5e96c7cb15765e1627',
    messagingSenderId: '64723911142',
    projectId: 'proaluno-81799',
    storageBucket: 'proaluno-81799.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmVT6Xpm3Ve7-e2DHvcC3q3Z2mD4CvV18',
    appId: '1:64723911142:ios:634d5e96c7cb15765e1627',
    messagingSenderId: '64723911142',
    projectId: 'proaluno-81799',
    storageBucket: 'proaluno-81799.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDYbMxAPny_Kz5AbwUQpR9Kan6ZFgt080',
    appId: '1:64723911142:web:4a2e41ccda79ce0f5e1627',
    messagingSenderId: '64723911142',
    projectId: 'proaluno-81799',
    authDomain: 'proaluno-81799.firebaseapp.com',
    storageBucket: 'proaluno-81799.firebasestorage.app',
    measurementId: 'G-96MZC9YSH6',
  );

}